server {
    listen 80;
    root /var/www/localhost/htdocs;
    index index.php index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        include fastcgi_params;
        # 'web' is the service name from docker-compose.yml
        fastcgi_pass web:8080; 
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}