version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-server
    ports:
      - "8080:80"
    volumes:
      - ./php-app:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  php:
    image: nisahello/php-fpm:latest
    container_name: php-fpm
    volumes:
      - ./php-app:/var/www/html
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: sre
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: admin_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d # Script to create users
    command: >
      postgres 
      -c max_connections=500

volumes:
  postgres_data: