version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      # Initial Admin/Full Access User
      - POSTGRES_DB=sre
      - POSTGRES_USER=admin_user
      - POSTGRES_PASSWORD=admin_password
    ports:
      - "5432:5432" # Mapping PostgreSQL port to host
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d # Location for user/DB setup script
    command: >
      postgres 
      -c max_connections=500 
      -c shared_buffers=256MB

volumes:
  postgres_data: