name: CI/CD Pipeline

on:
  push:
    paths:
      - '**/Dockerfile*'
      - '**/docker-compose.yaml'

# This line removes the warning message
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      dockerfile_changed: ${{ steps.filter.outputs.dockerfile }}
      compose_changed: ${{ steps.filter.outputs.compose }}
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            dockerfile:
              - '**/Dockerfile*'
            compose:
              - '**/docker-compose.yaml'

  build:
    needs: check_changes
    if: needs.check_changes.outputs.dockerfile_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build Docker Image
        run: docker build -t my-image .

  deploy:
    needs: [check_changes, build]
    if: |
      always() &&
      (needs.build.result == 'success' || needs.build.result == 'skipped') &&
      (needs.check_changes.outputs.dockerfile_changed == 'true' || needs.check_changes.outputs.compose_changed == 'true')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Deploy
        run: docker compose up -d